on: workflow_dispatch
jobs:
  start_release:
    name: Start release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print info
        run: |
          echo GITHUB_REF: $GITHUB_REF
          echo github.ref: ${{ github.ref }}
      - name: Trigger release workflow
        uses: adityakar/workflow-dispatcher@v1.0
        with:
          owner: mkindahl
          token: ${{ secrets.PERSONAL_TOKEN }}
          repo: ubiquitous-train
          event_type: trigger-release
          client_payload: '{"ref": "${{ github.ref }}"}'
      - name: All done
        run: |
          echo "All done"
