on: workflow_dispatch
jobs:
  name: Start release $GITHUB_REF
  steps:
    - uses: actions/checkout@v2
    - run: |
        echo GITHUB_REF: $GITHUB_REF
        echo github.ref: ${{ github.ref }}
    - uses: peter-evans/repository-dispatch@v1
      name: Trigger release workflow
      with:
        token: ${{ secrets.REPO_GHA_PAT }}
        repository: mkindahl/ubiquitous-train
        event-type: trigger-release
        client-payload: '{"ref": "${{ github.ref }}"}'    
