name: Trigger Pipeline
on:
  workflow_dispatch:
    inputs:
      upload-artifacts:
        description: 'Upload artifacts'
        required: false
        default: false
jobs:
  start_release:
    name: Start release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print info
        run: |
          echo GITHUB_REF: $GITHUB_REF
          echo github.ref: ${{ github.ref }}
      - name: Show event
        run: |
          cat <<EOT
          ${{ toJSON(github.event.inputs) }}
          EOT
          echo Upload: ${{ github.event.inputs.upload-artifacts }}
      - name: Trigger release workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mkindahl/ubiquitous-train
          event-type: trigger-release
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "upload-artifacts": "${{ github.event.inputs.upload-artifacts }}"
            }
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: All done
        run: |
          echo "All done"
