on: workflow_dispatch
jobs:
  start_release:
    name: Start release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print info
        run: |
          echo GITHUB_REF: $GITHUB_REF
          echo github.ref: ${{ github.ref }}
      - uses: peter-evans/repository-dispatch@v1
        name: Trigger release workflow
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: mkindahl/ubiquitous-train
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}"}'
