name: Run Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
jobs:
  check:
    name: Check repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print info
        run: |
          echo GITHUB_REF: $GITHUB_REF
          echo github.ref: ${{ github.ref }}
  release:
    name: Release it
    uses: mkindahl/ubiquitous-train/.github/workflows/release.yaml@v1
    needs: check
    with:
      version: ${{ github.event.inputs.version }}
      magic: ${{ github.ref }}

  notify:
    uses: mkindahl/solid-disco/.github/workflows/notify.yaml@main
    needs: release
    with:
      message: Release ${{ github.event.inputs.version }} done
